apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: monitoring

resources:
  - loki
  - promtail
  - grafana
  - ../monitoring/ingress

# Common labels for all monitoring components
commonLabels:
  app.kubernetes.io/part-of: monitoring

namespace: monitoring
