apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: metrics-server

resources:
  - rbac.yaml
  - deployment.yaml
  - apiservice.yaml
  - service.yaml

# Optional: Add common labels
commonLabels:
  app.kubernetes.io/name: metrics-server
  app.kubernetes.io/instance: metrics-server
  app.kubernetes.io/version: "v0.6.4"
  app.kubernetes.io/component: metrics-server
  k8s-app: metrics-server
