apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-meta-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - staging.video-meta.example.com
      secretName: staging-tls
  rules:
    - host: staging.video-meta.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: video-meta-app
                port:
                  number: 3000
