apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: loki

resources:
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - pvc.yaml

# Common labels for Loki components
commonLabels:
  app.kubernetes.io/name: loki
  app.kubernetes.io/instance: loki
  app.kubernetes.io/component: log-aggregation
  app.kubernetes.io/part-of: monitoring

namespace: monitoring
