apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include all component directories (namespace defined in overlays)
resources:
  - app/
  - postgres/
  - minio/

# Common labels for all resources
labels:
  - pairs:
      app.kubernetes.io/name: video-meta-app
      app.kubernetes.io/component: application

# Common annotations
commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: video-meta-app