apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ingress-nginx

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

# Optional: Add common labels
commonLabels:
  app.kubernetes.io/name: ingress-nginx
  app.kubernetes.io/instance: ingress-nginx
  app.kubernetes.io/version: "1.9.6"
  app.kubernetes.io/component: controller
  app.kubernetes.io/part-of: ingress-nginx
